# Generated by Django 3.2.13 on 2023-02-20 18:07

from django.db import migrations, models
import django.utils.timezone
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0005_auto_20220424_2025'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('project_name', models.CharField(max_length=50)),
                ('project_description', models.CharField(max_length=100)),
                ('project_type', models.CharField(choices=[('Android App', 'Android App'), ('Desktop App', 'Desktop App'), ('Web App', 'Web App'), ('IOS App', 'IOS App'), ('Terminal Code', 'Terminal Code')], default='Web App', max_length=20)),
                ('image', models.ImageField(default='projects/image/default.jpg', upload_to='projects/image')),
                ('project_url', models.CharField(blank=True, max_length=255, null=True)),
                ('github_url', models.CharField(blank=True, max_length=255, null=True)),
                ('video_url', models.CharField(blank=True, max_length=255, null=True)),
                ('language_used', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
