# Generated by Django 3.2.13 on 2023-02-21 03:40

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_description',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
