# Generated by Django 5.0.7 on 2025-01-24 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_programminglanguage_project_sub_project_title_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='language_used',
        ),
        migrations.AddField(
            model_name='project',
            name='language_used',
            field=models.ManyToManyField(to='projects.programminglanguage'),
        ),
    ]
