# Generated by Django 5.0.7 on 2025-01-25 16:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_category_alter_post_category'),
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='category.category'),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
