# Generated by Django 3.2.13 on 2023-02-22 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0002_alter_mydetail_whatsapp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='default_price',
            field=models.IntegerField(default=80),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='medium_price',
            field=models.IntegerField(default=20),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='urgent_price',
            field=models.IntegerField(default=40),
        ),
    ]
