# Generated by Django 3.2.13 on 2023-02-22 18:13

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0003_auto_20230222_1756'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(default='Description'),
        ),
    ]
