# Generated by Django 5.0.7 on 2025-01-21 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0004_assignment_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='mydetail',
            name='address',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='mydetail',
            name='coding_started_at',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='mydetail',
            name='contact_number',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='mydetail',
            name='country',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='mydetail',
            name='cv',
            field=models.FileField(default='cv/default.pdf', upload_to='cv'),
        ),
        migrations.AddField(
            model_name='mydetail',
            name='display_photo',
            field=models.ImageField(default='image/default.jpg', upload_to='image'),
        ),
        migrations.AddField(
            model_name='mydetail',
            name='dob',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='mydetail',
            name='email',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='mydetail',
            name='state',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
