# Generated by Django 5.0.7 on 2025-01-21 16:16

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0006_alter_mydetail_options_mydetail_about_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mydetail',
            name='slogon',
            field=ckeditor_uploader.fields.RichTextUploadingField(default='Slogon'),
        ),
    ]
