# Generated by Django 5.0.7 on 2025-01-21 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0008_remove_mydetail_nick_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='mydetail',
            name='nick_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
