# Generated by Django 5.0.7 on 2025-01-21 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0009_mydetail_nick_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='mydetail',
            name='logo',
            field=models.ImageField(default='image/default.jpg', upload_to='image'),
        ),
    ]
