# Generated by Django 5.0.7 on 2025-01-22 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0011_knowledge'),
    ]

    operations = [
        migrations.AddField(
            model_name='mydetail',
            name='second_display_photo',
            field=models.ImageField(default='image/default.jpg', upload_to='image'),
        ),
    ]
