# Generated by Django 5.0.7 on 2025-01-22 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0014_skill'),
    ]

    operations = [
        migrations.AddField(
            model_name='mydetail',
            name='country_code',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
