# Generated by Django 5.0.7 on 2025-01-22 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0015_mydetail_country_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='mydetail',
            name='instagram_url',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='mydetail',
            name='linkedin_url',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
