# Generated by Django 5.0.7 on 2025-01-22 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0016_mydetail_instagram_url_mydetail_linkedin_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='mydetail',
            name='google_map_url',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='mydetail',
            name='latitude',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='mydetail',
            name='longitude',
            field=models.FloatField(null=True),
        ),
    ]
