# Generated by Django 5.0.7 on 2025-01-26 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0017_mydetail_google_map_url_mydetail_latitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mydetail',
            name='logo',
            field=models.FileField(default='image/default.jpg', upload_to='image'),
        ),
    ]
