# Generated by Django 3.2.13 on 2023-02-21 07:06

import ckeditor_uploader.fields
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('assignment_title', models.CharField(max_length=100)),
                ('assignment_description', ckeditor_uploader.fields.RichTextUploadingField()),
                ('assignment_priority', models.CharField(choices=[('Urgent', 'Urgent'), ('Medium', 'Medium'), ('With In 15 Days', 'With In 15 Days'), ('With In 1 month', 'With In 1 month')], max_length=100)),
                ('email', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=100)),
                ('contact_no', models.CharField(max_length=100)),
                ('file', models.FileField(upload_to='')),
                ('assignment_status', models.CharField(choices=[('Pending', 'Pending'), ('Working On', 'Working On'), ('Delivered', 'Delivered')], max_length=100)),
                ('price', models.IntegerField(default=80)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
