# Generated by Django 3.2.13 on 2023-02-23 04:03

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0005_auto_20220424_2025'),
        ('assignments', '0010_alter_assignment_date_up_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='language_used',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='date_up_to',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 23, 4, 3, 52, 989765, tzinfo=utc)),
        ),
    ]
